version: '3.8'
services:
  node-app:
    build: .
    ports:
      - '3000:3000'
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    environment:
      NODE_ENV: test
  redis:
    image: 'redis:latest'
    environment:
      REDIS_HOST: redis
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
